INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (1, 1, 'Apple iPhone 13', 'Electronics', 100);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (2, 2, 'Nike Running Shoes', 'Footwear', 200);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (3, 3, 'Samsung Galaxy S21', 'Electronics', 150);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (4, 4, 'Adidas Soccer Ball', 'Sports', 250);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (5, 5, 'Sony WH-1000XM4', 'Electronics', 300);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (6, 6, 'Dell XPS 13', 'Electronics', 120);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (7, 7, 'Levi 501 Jeans', 'Apparel', 180);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (8, 8, 'Bose QuietComfort 35', 'Electronics', 140);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (9, 9, 'Canon EOS R5', 'Electronics', 90);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (10, 10, 'Ray-Ban Aviator Sunglasses', 'Accessories', 160);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (11, 11, 'Apple MacBook Pro', 'Electronics', 110);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (12, 12, 'Under Armour T-Shirt', 'Apparel', 220);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (13, 13, 'Fitbit Charge 4', 'Electronics', 130);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (14, 14, 'Sony PlayStation 5', 'Electronics', 80);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (15, 15, 'Timberland Boots', 'Footwear', 170);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (16, 16, 'GoPro HERO9', 'Electronics', 100);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (17, 17, 'North Face Jacket', 'Apparel', 190);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (18, 18, 'Microsoft Surface Pro 7', 'Electronics', 150);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (19, 19, 'Patagonia Backpack', 'Accessories', 140);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (20, 20, 'Samsung QLED TV', 'Electronics', 70);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (21, 21, 'Nike Air Max 270', 'Footwear', 200);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (22, 22, 'Garmin Forerunner 945', 'Electronics', 120);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (23, 23, 'Columbia Hiking Boots', 'Footwear', 160);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (24, 24, 'Apple Watch Series 6', 'Electronics', 130);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (25, 25, 'Adidas Ultraboost', 'Footwear', 180);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (26, 26, 'HP Spectre x360', 'Electronics', 110);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (27, 27, 'Oakley Sunglasses', 'Accessories', 150);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (28, 28, 'Sony Alpha a7 III', 'Electronics', 90);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (29, 29, 'New Balance 990v5', 'Footwear', 170);
INSERT INTO inventory (id, product_id, product_name, product_type, quantity) VALUES (30, 30, 'JBL Flip 5', 'Electronics', 140);
