# Payment service
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  type: ClusterIP
  selector:
    app: payment-svc
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc
  labels:
    app: payment-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-svc
  template:
    metadata:
      labels:
        app: payment-svc
    spec:
      containers:
        - name: payment-svc
          imagePullPolicy: IfNotPresent
          image: payment-svc:1.0.0
---
# Inventory service
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
spec:
  type: ClusterIP
  selector:
    app: inventory-svc
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc
  labels:
    app: inventory-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-svc
  template:
    metadata:
      labels:
        app: inventory-svc
    spec:
      containers:
        - name: inventory-svc
          imagePullPolicy: IfNotPresent
          image: inventory-svc:1.0.0
---
# Order service
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  type: ClusterIP
  selector:
    app: order-svc
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  labels:
    app: order-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
        - name: order-svc
          imagePullPolicy: IfNotPresent
          image: order-svc:1.0.0